<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

  <ItemGroup>
    <ProjectReference Include="..\..\gateways\ApiGateway\ApiGateway.csproj" />
    <ProjectReference Include="..\..\services\messaging-service\MessagingService.csproj" />
    <ProjectReference Include="..\..\services\logging-service\LoggingService.csproj" />
    <ProjectReference Include="..\..\services\email-service\EmailService.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>0a839c9c-fd6a-4ef9-afe0-c9e6fed4e3af</UserSecretsId>
  </PropertyGroup>

</Project>
